Variable number of image cells, lazy default hash
stewartlord/identicon.js pull request #24
Opened 2017-01-21 16:08 UTC by programWhiz

2017-01-24 07:35 UTC, stewartlord commented
Hi, just taking a look at this PR and I'm a bit unclear on what effect num-cells is supposed to achieve. It will produce a different looking image, but without other changes it is still the same number of cells that will be drawn, just in different positions.

2017-01-24 12:32 UTC, programWhiz commented
Right you are, looks like this part needs a change as well:
`var i, color;
            for (i = 0; i < 15; i++) {
                color = parseInt(this.hash.charAt(i), 16) % 2 ? bg : fg;
                if (i < numCells) {
                    this.rectangle(2 * cell + margin, i * cell + margin, cell, cell, color, image);
                } else if (i < 10) {
                    this.rectangle(1 * cell + margin, (i - numCells) * cell + margin, cell, cell, color, image);
                    this.rectangle(3 * cell + margin, (i - numCells) * cell + margin, cell, cell, color, image);
                } else if (i < 15) {
                    this.rectangle(0 * cell + margin, (i - 10) * cell + margin, cell, cell, color, image);
                    this.rectangle(4 * cell + margin, (i - 10) * cell + margin, cell, cell, color, image);
                }
            }`

2017-01-24 12:51 UTC, programWhiz commented
Ok that should fix it.  Also now the code is simpler.  Algorithm works like this now:
1. Iterate each row, and half the columns
2. Choose color for <row, col> (approximately what you were doing before)
3. Draw cell for the <row, col>, mirror about the center (for col=w/2, this will be a duplicate op, but its a bit simpler)
<img width="64" alt="screen shot 2017-01-24 at 6 51 16 am" src="https://cloud.githubusercontent.com/assets/13732159/22247860/9069c916-e201-11e6-977a-ef5bb7bf6c52.png">
<img width="53" alt="screen shot 2017-01-24 at 6 51 22 am" src="https://cloud.githubusercontent.com/assets/13732159/22247861/906de0b4-e201-11e6-90b0-75ff614e4fff.png">

2017-02-05 06:44 UTC, stewartlord commented on identicon.js
> +        this.numCells    = this.options.numCells   || this.defaults.numCells;
I don't think `numCells` is an accurate name for what this variable represents. Is it perhaps `squareSize`?

2017-02-05 06:47 UTC, stewartlord commented on identicon.js
> +                color = parseInt(this.hash.charAt(hashIdx), 16) % 2 ? bg : fg;
What happens if `hashIdx` exceeds the length of the hash?

2017-02-05 06:47 UTC, stewartlord commented on identicon.js
> +            var halfWidth = (numCells-1) / 2;
Could you add a comment briefly explaining how this drawing algorithm works?

2017-02-05 06:49 UTC, stewartlord commented on identicon.js
> +                color = parseInt(this.hash.charAt(hashIdx), 16) % 2 ? bg : fg;
It looks like `color` is no longer being declared.

2017-02-05 06:50 UTC, stewartlord commented on identicon.js
> +            var i, j, hashIdx;
Instead of `hashIdx`, perhaps `hashIndex`

2017-02-05 06:51 UTC, stewartlord requested changes
Thanks! Back to you :)

2017-04-29 23:43 UTC, closed without merging